services:

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/uploads:/app/uploads

    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

  frontend:
    build:
      context: ./frontend/web

    ports:
      - "8080:80"

    depends_on:
      - backend